apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80  # Matches Nginx
    protocol: TCP
  selector:
    app: my-app  # Matches deployment labels
