name: Deploy to EKS
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Apply Terraform
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve
    - name: Deploy Kubernetes
      run: |
        aws eks update-kubeconfig --name my-eks-cluster --region us-west-2
        kubectl apply -f kubernetes/
